SELECT
	PLAYER_NAME,
	COUNT(SCORE) AS SCORE_CT,
	AVG(SCORE) AS SCORE_AVG,
	STDEV(SCORE) AS ST_DEV
FROM DAILY_SCORES
GROUP BY PLAYER_NAME
HAVING COUNT(SCORE) > 1
ORDER BY
	STDEV(SCORE) ASC,
	COUNT(SCORE) DESC