SELECT
	PLAYER_NAME,
	COUNT(SCORE) AS SCORE_CT,
	AVG(SCORE) AS SCORE_AVG,
	MAX(MED) AS SCORE_MED,
	STDEV(SCORE) AS ST_DEV,
	MIN(SCORE) AS SCORE_MIN,
	MAX(SCORE) AS SCORE_MAX,
	MIN(DATE) AS DATE_MIN,
	MAX(DATE) AS DATE_MAX,
	MIN(PLAYER_ELO) AS ELO_MIN,
	MAX(PLAYER_ELO) AS ELO_MAX,
	MAX(PLAYER_ELO) - MIN(PLAYER_ELO) AS ELO_CHANGE
FROM
	(
	SELECT
		PLAYER_NAME,
		SCORE,
		PLAYER_ELO,
		CASE
			WHEN COMPLETED_GAMES IS NOT NULL THEN DATE
			ELSE NULL
		END AS DATE,
		PERCENTILE_CONT(0.5)
			WITHIN GROUP (ORDER BY SCORE)
			OVER (PARTITION BY PLAYER_NAME)
			AS MED
		FROM DAILY_SCORES
	) AS SCORES
WHERE PLAYER_NAME IN
	(
	SELECT PLAYER_NAME
	FROM DAILY_SCORES
	WHERE COMPETITIVE = 1
	GROUP BY PLAYER_NAME
	)
GROUP BY PLAYER_NAME
HAVING COUNT(SCORE) > 1
ORDER BY ELO_CHANGE DESC