SELECT
	PLAYER_NAME,
	COUNT(SCORE) AS SCORE_CT,
	AVG(SCORE) AS SCORE_AVG,
	MAX(MED) AS SCORE_MED,
	STDEV(SCORE) AS ST_DEV,
	MIN(SCORE) AS SCORE_MIN,
	MAX(SCORE) AS SCORE_MAX
FROM
	(
	SELECT
		DATE,
		PLAYER_NAME,
		SCORE,
		DATEADD(day, -30, CAST(GETDATE() AS date)) AS MINUS_THIRTY_DAYS,
		PERCENTILE_CONT(0.5)
			WITHIN GROUP (ORDER BY SCORE)
			OVER (PARTITION BY PLAYER_NAME)
			AS MED
		FROM DAILY_SCORES
		WHERE DATE >= DATEADD(day, -90, CAST(GETDATE() AS date))
	) AS SCORES
GROUP BY PLAYER_NAME
HAVING
	COUNT(SCORE) > 1
	AND MAX(DATE) >= MAX(MINUS_THIRTY_DAYS)
	AND (
		STDEV(SCORE) <= 80
		OR MAX(MED) >= 24990
		)
ORDER BY
	SUM(SCORE) DESC
	