SELECT
	PLAYER_NAME,
	COUNT(SCORE) AS SCORE_CT,
	AVG(SCORE) AS SCORE_AVG,
	AVG(MED) AS SCORE_MED,
	STDEV(SCORE) AS ST_DEV,
	MIN(SCORE) AS SCORE_MIN,
	MAX(SCORE) AS SCORE_MAX
FROM
	(
	SELECT
		PLAYER_NAME,
		SCORE,
		PERCENTILE_CONT(0.5)
			WITHIN GROUP (ORDER BY SCORE)
			OVER (PARTITION BY PLAYER_NAME)
			AS MED
		FROM DAILY_SCORES
	) AS SCORES
GROUP BY PLAYER_NAME
HAVING
	COUNT(SCORE) > 1
	AND STDEV(SCORE) < 100
ORDER BY
	SCORE_MED DESC,
	STDEV(SCORE) ASC,
	COUNT(SCORE) DESC