SELECT
	PLAYER_NAME,
	MAX(DATE) AS LAST_SEEN,
	COUNT(SCORE) AS SCORE_CT,
	AVG(SCORE) AS SCORE_AVG,
	STDEV(SCORE) AS ST_DEV,
	MAX(COMPLETED_GAMES) AS GAMES_CT,
	MAX(PLAYER_ELO) AS MAX_ELO,
	COUNT(CASE WHEN COMPETITIVE = 1 THEN 1 END) AS COMP_CT
FROM
	(
	SELECT
		*,
		PERCENTILE_CONT(0.5)
			WITHIN GROUP (ORDER BY COMPLETED_GAMES)
			OVER ()
			AS MED
	FROM DAILY_SCORES
	) AS SCORES
GROUP BY PLAYER_NAME
HAVING MAX(COMPLETED_GAMES) < AVG(MED)
ORDER BY
	COMP_CT DESC,
	GAMES_CT ASC
