SELECT
	PLAYER_NAME,
	COUNT(SCORE) AS SCORE_CT,
	AVG(SCORE) AS SCORE_AVG,
	STDEV(SCORE) AS SCORE_DEV
FROM DAILY_SCORES
GROUP BY PLAYER_NAME
HAVING
	COUNT(SCORE) > 1
	AND STDEV(SCORE) > 100
ORDER BY
	COUNT(SCORE) DESC,
	AVG(SCORE) DESC