DECLARE @date DATE = CAST('2023-07-01' AS DATE)

SELECT
	PLAYER_NAME,
	COUNT(SCORE) AS SCORE_CT,
	AVG(SCORE) AS SCORE_AVG,
	MAX(MED) AS SCORE_MED,
	STDEV(SCORE) AS ST_DEV,
	MIN(SCORE) AS SCORE_MIN,
	MAX(SCORE) AS SCORE_MAX
FROM
	(
	SELECT
		DATE,
		PLAYER_NAME,
		SCORE,
		DATEPART(YEAR, DATE) AS Y,
		DATEPART(QUARTER, DATE) AS Q,
		PERCENTILE_CONT(0.5)
			WITHIN GROUP (ORDER BY SCORE)
			OVER (PARTITION BY PLAYER_NAME)
			AS MED
		FROM DAILY_SCORES
		WHERE
			DATEPART(YEAR, DATE) = DATEPART(YEAR, @date)
			and DATEPART(QUARTER, DATE) = DATEPART(QUARTER, @date)
	) AS SCORES
GROUP BY PLAYER_NAME
HAVING
	COUNT(SCORE) > 1
	AND STDEV(SCORE) >= 80
	--AND MAX(MED) <= 24995
ORDER BY
	SUM(SCORE) DESC